--------------------------------------------------------
--  File created - Friday-May-19-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SURVEY
--------------------------------------------------------

  CREATE TABLE "TW"."SURVEY" 
   (	"ID" NUMBER, 
	"DIST_ID" NUMBER, 
	"DISTRICT" VARCHAR2(26 BYTE), 
	"QUESTION_TYPE" VARCHAR2(128 BYTE), 
	"ANSWER" VARCHAR2(128 BYTE), 
	"ANSWERS_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLICATIE" ;
REM INSERTING into TW.SURVEY
SET DEFINE OFF;
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (345,24,'Kavrepalanchok','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (346,24,'Kavrepalanchok','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (347,24,'Kavrepalanchok','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (348,24,'Kavrepalanchok','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (349,24,'Kavrepalanchok','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (350,24,'Kavrepalanchok','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (351,24,'Kavrepalanchok','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (352,24,'Kavrepalanchok','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (353,24,'Kavrepalanchok','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (354,24,'Kavrepalanchok','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (355,36,'Gorkha','problems_addressed','Don’t know',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (356,36,'Gorkha','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (357,36,'Gorkha','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (358,36,'Gorkha','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (359,36,'Gorkha','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (360,36,'Gorkha','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (361,36,'Gorkha','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (362,36,'Gorkha','rebuild_damage','3-Neutral',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (363,36,'Gorkha','rebuild_damage','Refused',12);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (364,36,'Gorkha','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (365,36,'Gorkha','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (366,36,'Gorkha','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (368,36,'Gorkha','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (369,36,'Gorkha','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (370,36,'Gorkha','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (371,36,'Gorkha','biggest_problem','Healthcare',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (372,36,'Gorkha','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (373,36,'Gorkha','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (374,36,'Gorkha','satisfied_government','Refused',5);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (375,36,'Gorkha','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (376,36,'Gorkha','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (377,36,'Gorkha','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (378,36,'Gorkha','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (379,36,'Gorkha','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (380,36,'Gorkha','satisfied_ngos','Refused',9);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (381,36,'Gorkha','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (382,36,'Gorkha','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (383,36,'Gorkha','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (384,36,'Gorkha','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (385,36,'Gorkha','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (386,36,'Gorkha','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (387,36,'Gorkha','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (388,36,'Gorkha','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (389,36,'Gorkha','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (390,36,'Gorkha','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (391,31,'Makwanpur','problems_addressed','Don’t know',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (392,31,'Makwanpur','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (393,31,'Makwanpur','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (394,31,'Makwanpur','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (395,31,'Makwanpur','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (396,31,'Makwanpur','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (397,31,'Makwanpur','rebuild_damage','Refused',12);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (398,31,'Makwanpur','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (399,31,'Makwanpur','rebuild_damage','Don''t know',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (400,31,'Makwanpur','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (401,31,'Makwanpur','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (402,31,'Makwanpur','biggest_problem','Livelihoods',7);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (404,31,'Makwanpur','biggest_problem','Housing inspections',21);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (405,31,'Makwanpur','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (406,31,'Makwanpur','biggest_problem','Toilets/sanitation',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (407,31,'Makwanpur','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (408,31,'Makwanpur','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (409,31,'Makwanpur','biggest_problem','Healthcare',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (410,31,'Makwanpur','biggest_problem','Clean water',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (411,31,'Makwanpur','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (412,31,'Makwanpur','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (413,31,'Makwanpur','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (414,31,'Makwanpur','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (415,31,'Makwanpur','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (416,31,'Makwanpur','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (417,31,'Makwanpur','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (418,31,'Makwanpur','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (419,31,'Makwanpur','satisfied_ngos','Refused',9);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (420,31,'Makwanpur','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (421,31,'Makwanpur','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (422,31,'Makwanpur','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (423,31,'Makwanpur','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (424,31,'Makwanpur','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (425,31,'Makwanpur','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (426,31,'Makwanpur','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (427,31,'Makwanpur','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (428,31,'Makwanpur','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (429,31,'Makwanpur','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (430,23,'Sindhupalchowk','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (431,23,'Sindhupalchowk','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (432,23,'Sindhupalchowk','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (433,23,'Sindhupalchowk','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (434,23,'Sindhupalchowk','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (435,23,'Sindhupalchowk','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (436,23,'Sindhupalchowk','rebuild_damage','Don''t know',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (437,23,'Sindhupalchowk','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (438,23,'Sindhupalchowk','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (440,23,'Sindhupalchowk','biggest_problem','Toilets/sanitation',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (441,23,'Sindhupalchowk','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (442,23,'Sindhupalchowk','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (443,23,'Sindhupalchowk','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (444,23,'Sindhupalchowk','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (445,23,'Sindhupalchowk','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (446,23,'Sindhupalchowk','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (447,23,'Sindhupalchowk','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (448,23,'Sindhupalchowk','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (449,23,'Sindhupalchowk','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (450,23,'Sindhupalchowk','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (451,23,'Sindhupalchowk','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (452,23,'Sindhupalchowk','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (453,23,'Sindhupalchowk','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (454,23,'Sindhupalchowk','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (455,23,'Sindhupalchowk','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (456,23,'Sindhupalchowk','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (457,23,'Sindhupalchowk','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (1,30,'Dhading','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (2,30,'Dhading','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (3,30,'Dhading','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (4,30,'Dhading','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (5,30,'Dhading','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (6,30,'Dhading','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (7,30,'Dhading','rebuild_damage','Refused',12);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (8,30,'Dhading','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (10,30,'Dhading','biggest_problem','Seeds and fertilizers',4);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (11,30,'Dhading','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (12,30,'Dhading','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (13,30,'Dhading','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (14,30,'Dhading','biggest_problem','Clean water',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (15,30,'Dhading','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (16,30,'Dhading','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (17,30,'Dhading','satisfied_government','Refused',5);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (18,30,'Dhading','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (19,30,'Dhading','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (20,30,'Dhading','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (21,30,'Dhading','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (22,30,'Dhading','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (23,30,'Dhading','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (24,30,'Dhading','satisfied_ngos','Refused',9);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (25,30,'Dhading','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (26,30,'Dhading','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (27,30,'Dhading','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (28,30,'Dhading','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (29,30,'Dhading','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (30,30,'Dhading','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (31,30,'Dhading','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (32,30,'Dhading','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (33,20,'Sindhuli','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (34,20,'Sindhuli','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (35,20,'Sindhuli','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (36,20,'Sindhuli','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (37,20,'Sindhuli','problems_addressed','3 – Neutral',1);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (38,20,'Sindhuli','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (39,20,'Sindhuli','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (40,20,'Sindhuli','rebuild_damage','3-Neutral',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (41,20,'Sindhuli','rebuild_damage','Don''t know',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (42,20,'Sindhuli','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (43,20,'Sindhuli','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (44,20,'Sindhuli','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (46,20,'Sindhuli','biggest_problem','Livelihoods',7);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (47,20,'Sindhuli','biggest_problem','Seeds and fertilizers',4);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (48,20,'Sindhuli','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (49,20,'Sindhuli','biggest_problem','Toilets/sanitation',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (50,20,'Sindhuli','biggest_problem','Psychosocial counseling',4);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (51,20,'Sindhuli','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (52,20,'Sindhuli','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (53,20,'Sindhuli','biggest_problem','Clean water',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (54,20,'Sindhuli','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (55,20,'Sindhuli','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (56,20,'Sindhuli','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (57,20,'Sindhuli','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (58,20,'Sindhuli','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (59,20,'Sindhuli','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (60,20,'Sindhuli','satisfied_ngos','Refused',9);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (61,20,'Sindhuli','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (62,20,'Sindhuli','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (63,20,'Sindhuli','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (64,20,'Sindhuli','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (65,20,'Sindhuli','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (66,20,'Sindhuli','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (67,20,'Sindhuli','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (68,20,'Sindhuli','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (69,20,'Sindhuli','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (70,26,'Bhaktapur','problems_addressed','Don’t know',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (71,26,'Bhaktapur','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (72,26,'Bhaktapur','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (73,26,'Bhaktapur','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (74,26,'Bhaktapur','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (75,26,'Bhaktapur','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (76,26,'Bhaktapur','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (77,26,'Bhaktapur','rebuild_damage','Refused',12);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (78,26,'Bhaktapur','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (79,26,'Bhaktapur','rebuild_damage','Don''t know',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (80,26,'Bhaktapur','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (81,26,'Bhaktapur','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (83,26,'Bhaktapur','biggest_problem','Housing inspections',21);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (84,26,'Bhaktapur','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (85,26,'Bhaktapur','biggest_problem','Toilets/sanitation',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (86,26,'Bhaktapur','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (87,26,'Bhaktapur','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (88,26,'Bhaktapur','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (89,26,'Bhaktapur','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (90,26,'Bhaktapur','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (91,26,'Bhaktapur','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (92,26,'Bhaktapur','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (93,26,'Bhaktapur','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (94,26,'Bhaktapur','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (95,26,'Bhaktapur','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (96,26,'Bhaktapur','satisfied_ngos','Refused',9);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (97,26,'Bhaktapur','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (98,26,'Bhaktapur','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (99,26,'Bhaktapur','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (100,26,'Bhaktapur','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (101,26,'Bhaktapur','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (102,26,'Bhaktapur','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (103,26,'Bhaktapur','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (104,26,'Bhaktapur','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (105,26,'Bhaktapur','support_provided','Refused',2);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (106,26,'Bhaktapur','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (107,26,'Bhaktapur','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (108,25,'Lalitpur','problems_addressed','Don’t know',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (109,25,'Lalitpur','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (110,25,'Lalitpur','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (111,25,'Lalitpur','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (112,25,'Lalitpur','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (113,25,'Lalitpur','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (114,25,'Lalitpur','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (115,25,'Lalitpur','rebuild_damage','3-Neutral',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (116,25,'Lalitpur','rebuild_damage','Don''t know',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (117,25,'Lalitpur','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (118,25,'Lalitpur','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (120,25,'Lalitpur','biggest_problem','Others',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (121,25,'Lalitpur','biggest_problem','Seeds and fertilizers',4);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (122,25,'Lalitpur','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (123,25,'Lalitpur','biggest_problem','Toilets/sanitation',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (124,25,'Lalitpur','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (125,25,'Lalitpur','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (126,25,'Lalitpur','biggest_problem','Clean water',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (127,25,'Lalitpur','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (128,25,'Lalitpur','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (129,25,'Lalitpur','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (130,25,'Lalitpur','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (131,25,'Lalitpur','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (132,25,'Lalitpur','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (133,25,'Lalitpur','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (134,25,'Lalitpur','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (135,25,'Lalitpur','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (136,25,'Lalitpur','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (137,25,'Lalitpur','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (138,25,'Lalitpur','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (139,25,'Lalitpur','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (140,25,'Lalitpur','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (141,25,'Lalitpur','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (142,25,'Lalitpur','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (143,25,'Lalitpur','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (144,29,'Rasuwa','problems_addressed','Don’t know',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (145,29,'Rasuwa','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (146,29,'Rasuwa','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (147,29,'Rasuwa','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (148,29,'Rasuwa','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (149,29,'Rasuwa','rebuild_damage','Don''t know',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (150,29,'Rasuwa','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (152,29,'Rasuwa','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (153,29,'Rasuwa','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (154,29,'Rasuwa','biggest_problem','Healthcare',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (155,29,'Rasuwa','biggest_problem','Clean water',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (156,29,'Rasuwa','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (157,29,'Rasuwa','satisfied_government','Refused',5);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (158,29,'Rasuwa','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (159,29,'Rasuwa','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (160,29,'Rasuwa','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (161,29,'Rasuwa','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (162,29,'Rasuwa','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (163,29,'Rasuwa','satisfied_ngos','Refused',9);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (164,29,'Rasuwa','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (165,29,'Rasuwa','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (166,29,'Rasuwa','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (167,29,'Rasuwa','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (168,29,'Rasuwa','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (169,29,'Rasuwa','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (170,29,'Rasuwa','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (171,29,'Rasuwa','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (172,21,'Ramechhap','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (173,21,'Ramechhap','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (174,21,'Ramechhap','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (175,21,'Ramechhap','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (176,21,'Ramechhap','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (177,21,'Ramechhap','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (178,21,'Ramechhap','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (180,21,'Ramechhap','biggest_problem','Livelihoods',7);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (181,21,'Ramechhap','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (182,21,'Ramechhap','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (183,21,'Ramechhap','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (184,21,'Ramechhap','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (185,21,'Ramechhap','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (186,21,'Ramechhap','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (187,21,'Ramechhap','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (188,21,'Ramechhap','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (189,21,'Ramechhap','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (190,21,'Ramechhap','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (191,21,'Ramechhap','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (192,21,'Ramechhap','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (193,21,'Ramechhap','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (194,21,'Ramechhap','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (195,21,'Ramechhap','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (196,21,'Ramechhap','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (197,21,'Ramechhap','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (198,21,'Ramechhap','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (199,27,'Kathmandu','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (200,27,'Kathmandu','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (201,27,'Kathmandu','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (202,27,'Kathmandu','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (203,27,'Kathmandu','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (204,27,'Kathmandu','rebuild_damage','3-Neutral',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (205,27,'Kathmandu','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (206,27,'Kathmandu','rebuild_damage','Don''t know',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (207,27,'Kathmandu','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (208,27,'Kathmandu','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (210,27,'Kathmandu','biggest_problem','Others',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (211,27,'Kathmandu','biggest_problem','Housing inspections',21);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (212,27,'Kathmandu','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (213,27,'Kathmandu','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (214,27,'Kathmandu','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (215,27,'Kathmandu','biggest_problem','Healthcare',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (216,27,'Kathmandu','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (217,27,'Kathmandu','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (218,27,'Kathmandu','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (219,27,'Kathmandu','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (220,27,'Kathmandu','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (221,27,'Kathmandu','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (222,27,'Kathmandu','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (223,27,'Kathmandu','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (224,27,'Kathmandu','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (225,27,'Kathmandu','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (226,27,'Kathmandu','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (227,27,'Kathmandu','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (228,27,'Kathmandu','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (229,27,'Kathmandu','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (230,27,'Kathmandu','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (231,28,'Nuwakot','problems_addressed','Don’t know',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (232,28,'Nuwakot','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (233,28,'Nuwakot','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (234,28,'Nuwakot','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (235,28,'Nuwakot','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (236,28,'Nuwakot','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (237,28,'Nuwakot','rebuild_damage','3-Neutral',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (238,28,'Nuwakot','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (239,28,'Nuwakot','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (240,28,'Nuwakot','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (242,28,'Nuwakot','biggest_problem','Livelihoods',7);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (243,28,'Nuwakot','biggest_problem','Housing inspections',21);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (244,28,'Nuwakot','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (245,28,'Nuwakot','biggest_problem','Toilets/sanitation',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (246,28,'Nuwakot','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (247,28,'Nuwakot','biggest_problem','Psychosocial counseling',4);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (248,28,'Nuwakot','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (249,28,'Nuwakot','biggest_problem','Healthcare',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (250,28,'Nuwakot','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (251,28,'Nuwakot','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (252,28,'Nuwakot','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (253,28,'Nuwakot','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (254,28,'Nuwakot','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (255,28,'Nuwakot','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (256,28,'Nuwakot','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (257,28,'Nuwakot','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (258,28,'Nuwakot','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (259,28,'Nuwakot','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (260,28,'Nuwakot','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (261,28,'Nuwakot','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (262,12,'Okhaldhunga','problems_addressed','Don’t know',13);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (263,12,'Okhaldhunga','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (264,12,'Okhaldhunga','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (265,12,'Okhaldhunga','problems_addressed','Refused',1);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (266,12,'Okhaldhunga','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (267,12,'Okhaldhunga','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (268,12,'Okhaldhunga','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (269,12,'Okhaldhunga','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (270,12,'Okhaldhunga','rebuild_damage','3-Neutral',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (271,12,'Okhaldhunga','rebuild_damage','Refused',12);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (272,12,'Okhaldhunga','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (273,12,'Okhaldhunga','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (274,12,'Okhaldhunga','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (276,12,'Okhaldhunga','biggest_problem','Housing inspections',21);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (277,12,'Okhaldhunga','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (278,12,'Okhaldhunga','biggest_problem','Financial support',98);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (279,12,'Okhaldhunga','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (280,12,'Okhaldhunga','biggest_problem','Healthcare',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (281,12,'Okhaldhunga','biggest_problem','Clean water',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (282,12,'Okhaldhunga','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (283,12,'Okhaldhunga','satisfied_government','Refused',5);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (284,12,'Okhaldhunga','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (285,12,'Okhaldhunga','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (286,12,'Okhaldhunga','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (287,12,'Okhaldhunga','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (288,12,'Okhaldhunga','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (289,12,'Okhaldhunga','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (290,12,'Okhaldhunga','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (291,12,'Okhaldhunga','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (292,12,'Okhaldhunga','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (293,12,'Okhaldhunga','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (294,12,'Okhaldhunga','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (295,12,'Okhaldhunga','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (296,12,'Okhaldhunga','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (297,12,'Okhaldhunga','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (298,22,'Dolakha','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (299,22,'Dolakha','problems_addressed','3 – Neutral',105);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (300,22,'Dolakha','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (301,22,'Dolakha','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (302,22,'Dolakha','problems_addressed','5 – Completely yes',35);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (303,22,'Dolakha','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (304,22,'Dolakha','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (306,22,'Dolakha','biggest_problem','Short-term shelter (tent/shelterbox)',101);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (307,22,'Dolakha','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (308,22,'Dolakha','biggest_problem','Healthcare',17);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (309,22,'Dolakha','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (310,22,'Dolakha','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (311,22,'Dolakha','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (312,22,'Dolakha','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (313,22,'Dolakha','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (314,22,'Dolakha','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (315,22,'Dolakha','satisfied_ngos','1 – Not at all',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (316,22,'Dolakha','satisfied_ngos','4–Mostly yes',536);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (317,22,'Dolakha','satisfied_ngos','2 – Not very much',237);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (318,22,'Dolakha','satisfied_ngos','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (319,22,'Dolakha','satisfied_ngos','5 – Completely yes',212);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (320,22,'Dolakha','support_provided','Don’t know',75);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (321,22,'Dolakha','support_provided','1 – Not at all',221);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (322,22,'Dolakha','support_provided','5 – Completely yes',288);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (323,22,'Dolakha','support_provided','3 – Neutral',111);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (324,22,'Dolakha','support_provided','4–Mostly yes',478);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (325,22,'Dolakha','support_provided','2 – Not very much',225);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (326,24,'Kavrepalanchok','problems_addressed','1 – Not at all',642);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (327,24,'Kavrepalanchok','problems_addressed','2 – Not very much',330);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (328,24,'Kavrepalanchok','problems_addressed','4– Mostly yes',273);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (329,24,'Kavrepalanchok','rebuild_damage','1-Completely yes',1080);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (330,24,'Kavrepalanchok','rebuild_damage','4-Not very much',71);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (331,24,'Kavrepalanchok','rebuild_damage','2-Somewhat yes',141);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (332,24,'Kavrepalanchok','rebuild_damage','5-Not at all',62);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (334,24,'Kavrepalanchok','biggest_problem','Psychosocial counseling',4);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (335,24,'Kavrepalanchok','biggest_problem','Long-term shelter (housing)',785);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (336,24,'Kavrepalanchok','satisfied_government','Don’t know',14);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (337,24,'Kavrepalanchok','satisfied_government','1 – Not at all',331);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (338,24,'Kavrepalanchok','satisfied_government','Refused',5);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (339,24,'Kavrepalanchok','satisfied_government','4–Mostly yes',501);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (340,24,'Kavrepalanchok','satisfied_government','5 – Completely yes',112);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (341,24,'Kavrepalanchok','satisfied_government','2 – Not very much',347);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (342,24,'Kavrepalanchok','satisfied_government','3 – Neutral',90);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (343,24,'Kavrepalanchok','satisfied_ngos','Don’t know',79);
Insert into TW.SURVEY (ID,DIST_ID,DISTRICT,QUESTION_TYPE,ANSWER,ANSWERS_COUNT) values (344,24,'Kavrepalanchok','satisfied_ngos','1 – Not at all',237);
--------------------------------------------------------
--  DDL for Index SYS_C008835
--------------------------------------------------------

  CREATE UNIQUE INDEX "TW"."SYS_C008835" ON "TW"."SURVEY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLICATIE" ;
--------------------------------------------------------
--  Constraints for Table SURVEY
--------------------------------------------------------

  ALTER TABLE "TW"."SURVEY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APLICATIE"  ENABLE;
